CREATE INDEX AR_INV_PMT_TI2 ON AR_INV_PMT_T(
        CUST_FIN_COA_CD,
        CUST_ORG_CD,
        CUST_NBR )
/
CREATE INDEX AR_INV_PMT_TI3 ON AR_INV_PMT_T(
        PRCS_FIN_COA_CD,
        PRCS_ORG_CD )
/
CREATE INDEX AR_INV_PMT_TI4 ON AR_INV_PMT_T(
        CUST_FIN_COA_CD,
        CUST_ORG_CD )
/
