CREATE INDEX CM_AST_PMT_DTL_TI2 ON CM_AST_PMT_DTL_T(
        FIN_COA_CD,
        ACCOUNT_NBR )
/
CREATE INDEX CM_AST_PMT_DTL_TI3 ON CM_AST_PMT_DTL_T(
        FDOC_POST_YR,
        FIN_COA_CD,
        FIN_OBJECT_CD )
/
