CREATE INDEX CM_CPTLAST_TI2 ON CM_CPTLAST_T(
        CPTLAST_IU_TAG_NBR)
/
CREATE INDEX CM_CPTLAST_TI3 ON CM_CPTLAST_T(
        AST_REP_UNVL_ID)
/
CREATE INDEX CM_CPTLAST_TI4 ON CM_CPTLAST_T(
        CAMPUS_CD, BLDG_CD, BLDG_ROOM_NBR)
/
