CREATE INDEX CM_CPTLAST_OBJ_TI2 ON CM_CPTLAST_OBJ_T(
        UNIV_FISCAL_YR,
        FIN_COA_CD,
        CPTLZTN_FOBJ_CD )
/
CREATE INDEX CM_CPTLAST_OBJ_TI3 ON CM_CPTLAST_OBJ_T(
        UNIV_FISCAL_YR,
        FIN_COA_CD,
        ACCUM_DEPR_FOBJ_CD )
/
CREATE INDEX CM_CPTLAST_OBJ_TI4 ON CM_CPTLAST_OBJ_T(
        UNIV_FISCAL_YR,
        FIN_COA_CD,
        DEPR_EXP_FOBJ_CD )
/
