CREATE INDEX PDP_PROC_SUM_TI2 ON PDP_PROC_SUM_T(
        DISB_TYP_CD )
/
CREATE INDEX PDP_PROC_SUM_TI3 ON PDP_PROC_SUM_T(
        CUST_ID )
/
CREATE INDEX PDP_PROC_SUM_TI4 ON PDP_PROC_SUM_T(
        PROC_ID )
/
