CREATE INDEX PDP_PMT_GRP_TI2 ON PDP_PMT_GRP_T(
        PMT_FIL_ID )
/
CREATE INDEX PDP_PMT_GRP_TI3 ON PDP_PMT_GRP_T(
        BNK_ID )
/
CREATE INDEX PDP_PMT_GRP_TI4 ON PDP_PMT_GRP_T(
        DISB_TYP_CD )
/
CREATE INDEX PDP_PMT_GRP_TI5 ON PDP_PMT_GRP_T(
        PMT_STAT_CD )
/
CREATE INDEX PDP_PMT_GRP_TI6 ON PDP_PMT_GRP_T(
        DISB_NBR )
/
CREATE INDEX PDP_PMT_GRP_TI7 ON PDP_PMT_GRP_T(
        PMT_PAYEE_NM )
/
CREATE INDEX PDP_PMT_GRP_TI8 ON PDP_PMT_GRP_T(
        PROC_ID )
/
