CREATE INDEX PDP_PMT_GRP_HIST_TI3 ON PDP_PMT_GRP_HIST_T(
        ORIG_PMT_STAT_CD )
/
CREATE INDEX PDP_PMT_GRP_HIST_TI4 ON PDP_PMT_GRP_HIST_T(
        PMT_CHG_CD )
/
CREATE INDEX PDP_PMT_GRP_HIST_TI5 ON PDP_PMT_GRP_HIST_T(
        ORIG_BNK_ID )
/
CREATE INDEX PDP_PMT_GRP_HIST_TI6 ON PDP_PMT_GRP_HIST_T(
        ORIG_DISB_TYP_CD )
/
CREATE INDEX PDP_PMT_GRP_HIST_TI7 ON PDP_PMT_GRP_HIST_T(
        ORIG_PROC_ID )
/
CREATE INDEX PDP_PMT_GRP_HIST_TI8 ON PDP_PMT_GRP_HIST_T(
        PMT_GRP_ID )
/
