CREATE INDEX PDP_CUST_BNK_TI3 ON PDP_CUST_BNK_T(
        CUST_ID )
/
CREATE INDEX PDP_CUST_BNK_TI4 ON PDP_CUST_BNK_T(
        BNK_ID )
/
CREATE INDEX PDP_CUST_BNK_TI5 ON PDP_CUST_BNK_T(
        DISB_TYP_CD )
/
