CREATE INDEX IDX_QRTZ_T_NEXT_FIRE_TIME ON QRTZ_TRIGGERS(NEXT_FIRE_TIME) 
/
CREATE INDEX IDX_QRTZ_T_STATE ON QRTZ_TRIGGERS(TRIGGER_STATE) 
/
CREATE INDEX IDX_QRTZ_T_NFT_ST ON QRTZ_TRIGGERS(NEXT_FIRE_TIME,TRIGGER_STATE) 
/
CREATE INDEX IDX_QRTZ_T_VOLATILE ON QRTZ_TRIGGERS(IS_VOLATILE) 
/
