ALTER TABLE AR_CSH_CTRL_T
ADD (CONSTRAINT AR_CSH_CTRL_TR1 FOREIGN KEY (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD ))
ADD (CONSTRAINT AR_CSH_CTRL_TR2 FOREIGN KEY (
      FDOC_NBR )
REFERENCES AR_DOC_HDR_T ( 
      FDOC_NBR ))
/
