ALTER TABLE AR_INV_PD_APLD_T
ADD (CONSTRAINT AR_INV_PD_APLD_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES AR_DOC_HDR_T ( 
      FDOC_NBR ))
ADD (CONSTRAINT AR_INV_PD_APLD_TR2 FOREIGN KEY (
      FDOC_REF_INV_NBR,
      AR_INV_ITM_NBR )
REFERENCES AR_INV_DTL_T (
      FDOC_NBR,
      AR_INV_ITM_NBR ))
ADD (CONSTRAINT AR_INV_PD_APLD_TR3 FOREIGN KEY (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD ))
/
