ALTER TABLE AR_NON_APLD_DIST_MT
ADD (CONSTRAINT AR_NON_APLD_DIST_MTR1 FOREIGN KEY (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD ))
/
