ALTER TABLE AR_NON_APLD_DIST_T
ADD (CONSTRAINT AR_NON_APLD_DIST_TR1 FOREIGN KEY (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR,
      UNIV_FISCAL_PRD_CD ))
ADD (CONSTRAINT AR_NON_APLD_DIST_TR2 FOREIGN KEY (
      FDOC_REF_NBR )
REFERENCES AR_NON_APLD_HLDG_T (
      FDOC_REF_NBR ))
/
