ALTER TABLE CM_AST_COMPONENT_T
ADD (CONSTRAINT CM_AST_COMPONENT_TR1 FOREIGN KEY (
      CPTLAST_NBR,
      CPTLAST_ORIGIN_CD )
REFERENCES CM_CPTLAST_T ( 
      CPTLAST_NBR,
      CPTLAST_ORIGIN_CD ))
ADD (CONSTRAINT CM_AST_COMPONENT_TR2 FOREIGN KEY (
      CACMP_COND_CD )
REFERENCES CM_AST_CONDITION_T ( 
      CPTLAST_COND_CD ))
/
