ALTER TABLE CM_AST_RPR_HIST_T
ADD (CONSTRAINT CM_AST_RPR_HIST_TR1 FOREIGN KEY (
      CPTLAST_NBR,
      CPTLAST_ORIGIN_CD )
REFERENCES CM_CPTLAST_T ( 
      CPTLAST_NBR,
      CPTLAST_ORIGIN_CD ))
/
