ALTER TABLE CM_AST_RETIREDOC_T
ADD (CONSTRAINT CM_AST_RETIREDOC_TR1 FOREIGN KEY (
      FS_ORIGIN_CD,
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T ( 
      FS_ORIGIN_CD,
      FDOC_NBR ))
ADD (CONSTRAINT CM_AST_RETIREDOC_TR2 FOREIGN KEY (
      AST_RETIRE_REAS_CD )
REFERENCES CM_RETIRE_REAS_T ( 
      AST_RETIRE_REAS_CD ))
/
