ALTER TABLE CM_CPTLAST_OBJ_T
ADD (CONSTRAINT CM_CPTLAST_OBJ_TR4 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT CM_CPTLAST_OBJ_TR5 FOREIGN KEY (
      FIN_OBJ_SUB_TYPE_CD )
REFERENCES CA_OBJ_SUB_TYPE_T (
      FIN_OBJ_SUB_TYP_CD ))
/
