ALTER TABLE CM_INVN_ERR_DTL_T
ADD (CONSTRAINT CM_INVN_ERR_DTL_TR1 FOREIGN KEY (
      AST_UPLDR_UNVL_ID, AST_UPLDR_SEQ_NBR, AST_UPLD_ROW_NBR )
REFERENCES CM_INVN_UPLD_DTL_T (
      AST_UPLDR_UNVL_ID, AST_UPLDR_SEQ_NBR, AST_UPLD_ROW_NBR ))
/
