ALTER TABLE CM_INVN_UPLD_DTL_T
ADD (CONSTRAINT CM_INVN_UPLD_DTL_TR1 FOREIGN KEY (
      AST_UPLDR_UNVL_ID, AST_UPLDR_SEQ_NBR )
REFERENCES CM_INVN_UPLD_HDR_T (
      AST_UPLDR_UNVL_ID, AST_UPLDR_SEQ_NBR ))
/
