ALTER TABLE CM_MULT_AST_HDR_T
ADD (CONSTRAINT CM_MULT_AST_HDR_TR1 FOREIGN KEY (
      FS_ORIGIN_CD,
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T ( 
      FS_ORIGIN_CD,
      FDOC_NBR ))
ADD (CONSTRAINT CM_MULT_AST_HDR_TR2 FOREIGN KEY (
      ORG_OWNER_COA_CD,
      ORG_OWNER_ACCT_NBR )
REFERENCES CA_ACCOUNT_T ( 
      FIN_COA_CD,
      ACCOUNT_NBR ))
/
