ALTER TABLE CM_PEND_AST_UPD_T
ADD (CONSTRAINT CM_PEND_AST_UPD_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT CM_PEND_AST_UPD_TR2 FOREIGN KEY (
      CPTLAST_NBR )
REFERENCES CM_CPTLAST_T (
      CPTLAST_NBR ))
/
