ALTER TABLE LD_A21_REPORT_T
ADD (CONSTRAINT LD_A21_REPORT_TR2 FOREIGN KEY (
      LBR_ET_FSCL_YR, LBR_ET_FSCL_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR, UNIV_FISCAL_PRD_CD ))
ADD (CONSTRAINT LD_A21_REPORT_TR3 FOREIGN KEY (
      LBR_RPT_PRDSTAT_CD )
REFERENCES LD_A21_PRD_STAT_T (
      LBR_RPT_PRDSTAT_CD ))
ADD (CONSTRAINT LD_A21_REPORT_TR4 FOREIGN KEY (
      A21_LBR_RPT_TYP_CD )
REFERENCES LD_A21_RPT_TYP_T (
      A21_LBR_RPT_TYP_CD ))
/