ALTER TABLE LD_BCN_ORG_RPTS_T
ADD (CONSTRAINT LD_BCN_ORG_RPTS_TR2 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT LD_BCN_ORG_RPTS_TR4 FOREIGN KEY (
      RPTS_TO_FIN_COA_CD, RPTS_TO_ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT LD_BCN_ORG_RPTS_TR5 FOREIGN KEY (
      RC_CD )
REFERENCES CA_RC_T (
      RC_CD ))
/
