ALTER TABLE LD_BCN_AF_REASON_T
ADD (CONSTRAINT LD_BCN_AF_REASON_TR6 FOREIGN KEY (
      APPT_FND_REASON_CD )
REFERENCES LD_BCN_AF_RSN_CD_T (
      APPT_FND_REASON_CD ))
ADD (CONSTRAINT LD_BCN_AF_REASON_TR7 FOREIGN KEY (
      UNIV_FISCAL_YR, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, POSITION_NBR, EMPLID )
REFERENCES LD_PNDBC_APPTFND_T (
      UNIV_FISCAL_YR, FIN_COA_CD, ACCOUNT_NBR, SUB_ACCT_NBR, FIN_OBJECT_CD, FIN_SUB_OBJ_CD, POSITION_NBR, EMPLID ))
/