ALTER TABLE LD_BCN_POS_T
ADD (CONSTRAINT LD_BCN_POS_TR1 FOREIGN KEY (
      UNIV_FISCAL_YR )
REFERENCES FS_OPTION_T (
      UNIV_FISCAL_YR ))
ADD (CONSTRAINT LD_BCN_POS_TR2 FOREIGN KEY (
      RC_CD )
REFERENCES CA_RC_T (
      RC_CD ))
/