ALTER TABLE AP_AUTO_APRV_EXCL_T
ADD (CONSTRAINT AP_AUTO_APRV_EXCL_TR1 FOREIGN KEY (
      FIN_COA_CD, ACCOUNT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR)) 
ADD (CONSTRAINT AP_AUTO_APRV_EXCL_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
/