ALTER TABLE AP_NEG_PMT_RQST_APRVL_LMT_T
ADD (CONSTRAINT AP_NEG_PMT_RQST_APRVL_LMT_TR1 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT AP_NEG_PMT_RQST_APRVL_LMT_TR2 FOREIGN KEY (
      FIN_COA_CD, ACCT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR ))
ADD (CONSTRAINT AP_NEG_PMT_RQST_APRVL_LMT_TR3 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
/