ALTER TABLE AP_PMT_CHG_ACCT_T
ADD (CONSTRAINT AP_PMT_CHG_ACCT_TR1 FOREIGN KEY (
      FS_ORIGIN_CD,
      FDOC_NBR,
      TRN_ENTR_SEQ_NBR )
REFERENCES GL_PENDING_ENTRY_T (
      FS_ORIGIN_CD,
      FDOC_NBR,
      TRN_ENTR_SEQ_NBR )) 
/
