ALTER TABLE AR_DOC_RCURRNC_T
ADD (CONSTRAINT AR_DOC_RCURRNC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT AR_DOC_RCURRNC_TR2 FOREIGN KEY (
      CUST_NBR )
REFERENCES AR_CUST_T ( 
      CUST_NBR ))
ADD (CONSTRAINT AR_DOC_RCURRNC_TR3 FOREIGN KEY (
      FDOC_REF_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
/
