ALTER TABLE CA_ACCT_CHG_DTL_T
ADD (CONSTRAINT CA_ACCT_CHG_DTL_TR1 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT CA_ACCT_CHG_DTL_TR2 FOREIGN KEY (
      FIN_COA_CD, ACCOUNT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR ))
ADD (CONSTRAINT CA_ACCT_CHG_DTL_TR3 FOREIGN KEY (
      FDOC_NBR )
REFERENCES CA_ACCT_CHG_DOC_T (
      FDOC_NBR ))
/