ALTER TABLE CA_HIGHR_ED_FUNC_T
ADD (CONSTRAINT CA_HIGHR_ED_FUNC_TR1 FOREIGN KEY (
      FIN_UBO_FUNC_CD )
REFERENCES CA_UBO_FUNC_T (
      FIN_UBO_FUNC_CD ))
ADD (CONSTRAINT CA_HIGHR_ED_FUNC_TR2 FOREIGN KEY (
      FIN_FED_FUNC_CD )
REFERENCES CA_FEDERAL_FUNC_T (
      FIN_FED_FUNC_CD ))
ADD (CONSTRAINT CA_HIGHR_ED_FUNC_TR3 FOREIGN KEY (
      FIN_AICPA_FUNC_CD )
REFERENCES CA_AICPA_FUNC_T (
      FIN_AICPA_FUNC_CD ))
/