ALTER TABLE CA_ORG_RTNG_MDL_NM_T
ADD (CONSTRAINT CA_ORG_RTNG_MDL_NM_TR1 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT CA_ORG_RTNG_MDL_NM_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
/