ALTER TABLE CA_ORG_RVRSN_CHG_DTL_T
  ADD (CONSTRAINT CA_ORG_RVRSN_CHG_DTL_TR1 FOREIGN KEY (
        ORG_RVRSN_CTGRY_CD)
  REFERENCES CA_ORG_RVRSN_CTGRY_T (
        ORG_RVRSN_CTGRY_CD))
  ADD (CONSTRAINT CA_ORG_RVRSN_CHG_DTL_TR2 FOREIGN KEY (
        FDOC_NBR)
  REFERENCES CA_ORG_RVRSN_CHG_DOC_T (
        FDOC_NBR))
/