ALTER TABLE CA_ORG_RVRSN_CHG_ORG_T
  ADD (CONSTRAINT CA_ORG_RVRSN_CHG_ORG_TR1 FOREIGN KEY (
        FIN_COA_CD)
  REFERENCES CA_CHART_T (
        FIN_COA_CD))
  ADD (CONSTRAINT CA_ORG_RVRSN_CHG_ORG_TR2 FOREIGN KEY (
        FIN_COA_CD, ORG_CD)
  REFERENCES CA_ORG_T (
        FIN_COA_CD, ORG_CD))
  ADD (CONSTRAINT CA_ORG_RVRSN_CHG_ORG_TR3 FOREIGN KEY (
        FDOC_NBR)
  REFERENCES CA_ORG_RVRSN_CHG_DOC_T (
        FDOC_NBR))
/