ALTER TABLE CA_ORG_EXTNS_T
ADD (CONSTRAINT CA_ORG_EXTNS_TR1 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT CA_ORG_EXTNS_TR3 FOREIGN KEY (
      IU_CAMPUS_CD )
REFERENCES SH_CAMPUS_T (
      CAMPUS_CD ))
/