ALTER TABLE CG_PRPSL_PRJDR_T
ADD (CONSTRAINT CG_PRPSL_PRJDR_TR1 FOREIGN KEY (
      PERSON_UNVL_ID )
REFERENCES CG_PRJDR_T (
      PERSON_UNVL_ID ))
ADD (CONSTRAINT CG_PRPSL_PRJDR_TR2 FOREIGN KEY (
      CGPRPSL_NBR )
REFERENCES CG_PRPSL_T (
      CGPRPSL_NBR ))
/