ALTER TABLE CG_PRPSL_ORG_T
ADD (CONSTRAINT CG_PRPSL_ORG_TR1 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT CG_PRPSL_ORG_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT CG_PRPSL_ORG_TR3 FOREIGN KEY (
      CGPRPSL_NBR )
REFERENCES CG_PRPSL_T (
      CGPRPSL_NBR ))
/