ALTER TABLE CG_PRPSL_SUBCN_T
ADD (CONSTRAINT CG_PRPSL_SUBCN_TR1 FOREIGN KEY (
      CG_SUBCNR_NBR )
REFERENCES CG_SUBCNR_T (
      CG_SUBCNR_NBR ))
ADD (CONSTRAINT CG_PRPSL_SUBCN_TR2 FOREIGN KEY (
      CGPRPSL_NBR )
REFERENCES CG_PRPSL_T (
      CGPRPSL_NBR ))
/