ALTER TABLE CM_AST_PMT_DOC_T
ADD (CONSTRAINT CM_AST_PMT_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT CM_AST_PMT_DOC_TR2 FOREIGN KEY (
      CPTLAST_NBR )
REFERENCES CM_CPTLAST_T (
      CPTLAST_NBR ))
/
