ALTER TABLE CM_CPTLAST_CHG_DOC_T
ADD (CONSTRAINT CM_CPTLAST_CHG_DOC_TR1 FOREIGN KEY (
      CPTLAST_TYP_CD )
REFERENCES CM_ASSET_TYPE_T (
      CPTLAST_TYP_CD ))
ADD (CONSTRAINT CM_CPTLAST_CHG_DOC_TR2 FOREIGN KEY (
      CPTLAST_COND_CD )
REFERENCES CM_AST_CONDITION_T (
      CPTLAST_COND_CD ))
/
