ALTER TABLE CM_FABR_RQST_DOC_T
ADD (CONSTRAINT CM_FABR_RQST_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT CM_FABR_RQST_DOC_TR2 FOREIGN KEY (
      CPTLAST_TYP_CD )
REFERENCES CM_ASSET_TYPE_T (
      CPTLAST_TYP_CD ))
ADD (CONSTRAINT CM_FABR_RQST_DOC_TR3 FOREIGN KEY (
      AST_OFFCMP_ST_CD )
REFERENCES SH_STATE_T (
      POSTAL_STATE_CD ))
/
