ALTER TABLE CM_MULT_AST_DOC_T
ADD (CONSTRAINT CM_MULT_AST_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT CM_MULT_AST_DOC_TR2 FOREIGN KEY (
      AST_INVN_STAT_CD )
REFERENCES CM_AST_STATUS_T (
      AST_INVN_STAT_CD ))
/
