ALTER TABLE CM_PRTG_TEMP_T
ADD (CONSTRAINT CM_PRTG_TEMP_TR1 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT CM_PRTG_TEMP_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
/
