ALTER TABLE FP_ADV_DPST_DTL_T
ADD (CONSTRAINT FP_ADV_DPST_DTL_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_CASH_RCPT_DOC_T (
      FDOC_NBR ))
ADD (CONSTRAINT FP_ADV_DPST_DTL_TR2 FOREIGN KEY (
      FDOC_BANK_CD )
REFERENCES FP_BANK_T (
      FDOC_BANK_CD ))
ADD (CONSTRAINT FP_ADV_DPST_DTL_TR3 FOREIGN KEY (
      FDOC_BANK_CD, FDOC_BANK_ACCT_NBR )
REFERENCES FP_BANK_ACCOUNT_T (
      FDOC_BANK_CD, FDOC_BANK_ACCT_NBR ))
/