ALTER TABLE FP_CR_CARD_DTL_T
ADD (CONSTRAINT FP_CR_CARD_DTL_TR1 FOREIGN KEY (
      FDOC_CCRD_TYP_CD )
REFERENCES FP_CR_CARD_TYP_T (
      FDOC_CCRD_TYP_CD ))
ADD (CONSTRAINT FP_CR_CARD_DTL_TR2 FOREIGN KEY (
      FDOC_CCRD_VNDR_NBR )
REFERENCES FP_CR_CARD_VNDR_T (
      FDOC_CCRD_VNDR_NBR ))
ADD (CONSTRAINT FP_CR_CARD_DTL_TR3 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_CASH_RCPT_DOC_T (
      FDOC_NBR ))
/