ALTER TABLE FP_DEPOSIT_DOC_T
ADD (CONSTRAINT FP_DEPOSIT_DOC_TR1 FOREIGN KEY (
      FDOC_DPST_BNK_CD, FDOC_BNK_ACCT_NBR )
REFERENCES FP_BANK_ACCOUNT_T (
      FDOC_BANK_CD, FDOC_BANK_ACCT_NBR ))
ADD (CONSTRAINT FP_DEPOSIT_DOC_TR2 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DEPOSIT_HDR_T (
      FDOC_NBR ))
/