ALTER TABLE FP_DV_DOC_T
ADD (CONSTRAINT FP_DV_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT FP_DV_DOC_TR2 FOREIGN KEY (
      DV_DOC_LOC_CD )
REFERENCES FP_DV_DOC_LOC_T (
      DV_DOC_LOC_CD ))
/