ALTER TABLE FP_DEP_CSH_RCPT_T
ADD (CONSTRAINT FP_DEP_CSH_RCPT_TR1 FOREIGN KEY (
      FDOC_DPST_NBR, FDOC_LINE_NBR )
REFERENCES FP_DEPOSIT_DOC_T (
      FDOC_NBR, FDOC_LINE_NBR ))
ADD (CONSTRAINT FP_DEP_CSH_RCPT_TR2 FOREIGN KEY (
      FDOC_CSH_RCPT_NBR )
REFERENCES FP_CASH_RCPT_HDR_T (
      FDOC_NBR ))
/