ALTER TABLE FP_FSCL_YR_CTRL_T
ADD (CONSTRAINT FP_FSCL_YR_CTRL_TR1 FOREIGN KEY (
      FS_FUNC_CTRL_CD )
REFERENCES FP_FUNC_CTRL_CD_T (
      FS_FUNC_CTRL_CD ))
ADD (CONSTRAINT FP_FSCL_YR_CTRL_TR2 FOREIGN KEY (
      UNIV_FISCAL_YR )
REFERENCES FS_OPTION_T (
      UNIV_FISCAL_YR ))
/