ALTER TABLE FP_JRNL_VCHR_DOC_T
ADD (CONSTRAINT FP_JRNL_VCHR_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT FP_JRNL_VCHR_DOC_TR2 FOREIGN KEY (
      FDOC_POST_YR, FDOC_POST_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR, UNIV_FISCAL_PRD_CD ))
ADD (CONSTRAINT FP_JRNL_VCHR_DOC_TR3 FOREIGN KEY (
      FIN_BALANCE_TYP_CD )
REFERENCES CA_BALANCE_TYPE_T (
      FIN_BALANCE_TYP_CD ))
/