ALTER TABLE FP_PRCRMNT_TRN_DTL_T
ADD (CONSTRAINT FP_PRCRMNT_TRN_DTL_TR1 FOREIGN KEY (
      FDOC_NBR, FDOC_TRN_LN_NBR )
REFERENCES FP_PRCRMNT_VNDR_T (
      FDOC_NBR, FDOC_TRN_LN_NBR ))
ADD (CONSTRAINT FP_PRCRMNT_TRN_DTL_TR2 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_PRCRMNT_DOC_T (
      FDOC_NBR ))
/