ALTER TABLE FP_PRCRMNT_DOC_T
ADD (CONSTRAINT FP_PRCRMNT_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT FP_PRCRMNT_DOC_TR2 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_PRCRMNT_CARD_HLDR_T (
      FDOC_NBR ))
/