ALTER TABLE FP_RPT_CD_T
ADD (CONSTRAINT FP_RPT_CD_TR1 FOREIGN KEY (
      FIN_RPT_CHRT_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT FP_RPT_CD_TR2 FOREIGN KEY (
      FIN_RPT_CHRT_CD, FIN_RPT_ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT FP_RPT_CD_TR4 FOREIGN KEY (
      FIN_RPT_CHRT_CD, FIN_RPT_ORG_CD, FIN_RPTS_TO_RPT_CD )
REFERENCES FP_RPT_CD_T (
      FIN_RPT_CHRT_CD, FIN_RPT_ORG_CD, FIN_RPT_CD ))
/