ALTER TABLE GL_ORG_RVRSN_UNIT_WRK_T
ADD (CONSTRAINT GL_ORG_RVRSN_UNIT_WRK_TR1 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT GL_ORG_RVRSN_UNIT_WRK_TR2 FOREIGN KEY (
      FIN_COA_CD, ACCOUNT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR ))
/