ALTER TABLE LD_A21_DTL_BLD_T
ADD (CONSTRAINT LD_A21_DTL_BLD_TR1 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT LD_A21_DTL_BLD_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT LD_A21_DTL_BLD_TR4 FOREIGN KEY (
      A21_LBR_RPT_NBR, A21_LBR_FSCL_YR )
REFERENCES LD_A21_REPORT_T (
      A21_LBR_RPT_NBR, UNIV_FISCAL_YR ))
/
