ALTER TABLE LD_A21_RPT_PRD_T
ADD (CONSTRAINT LD_A21_RPT_PRD_TR1 FOREIGN KEY (
      A21LBR_RPT_FSCL_YR, LBR_RPT_FSCLPRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR, UNIV_FISCAL_PRD_CD ))
/