ALTER TABLE LD_BCN_ACCT_RPTS_T
ADD (CONSTRAINT LD_BCN_ACCT_RPTS_TR1 FOREIGN KEY (
      FIN_COA_CD, ACCOUNT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR ))
ADD (CONSTRAINT LD_BCN_ACCT_RPTS_TR3 FOREIGN KEY (
      RPTS_TO_FIN_COA_CD, RPTS_TO_ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
ADD (CONSTRAINT LD_BCN_ACCT_RPTS_TR5 FOREIGN KEY (
      RPTS_TO_FIN_COA_CD, RPTS_TO_ORG_CD )
REFERENCES LD_BCN_ORG_RPTS_T (
      FIN_COA_CD, ORG_CD ))
/
