ALTER TABLE LD_BENEFITS_CALC_T
ADD (CONSTRAINT LD_BENEFITS_CALC_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT LD_BENEFITS_CALC_TR3 FOREIGN KEY (
      POS_BENEFIT_TYP_CD )
REFERENCES LD_BENEFITS_TYPE_T (
      POS_BENEFIT_TYP_CD ))
ADD (CONSTRAINT LD_BENEFITS_CALC_TR4 FOREIGN KEY (
      UNIV_FISCAL_YR )
REFERENCES FS_OPTION_T (
      UNIV_FISCAL_YR ))
/