ALTER TABLE LD_CSFTRCKR_OVRD_T
ADD (CONSTRAINT LD_CSFTRCKR_OVRD_TR1 FOREIGN KEY (
      UNIV_FISCAL_YR )
REFERENCES FS_OPTION_T (
      UNIV_FISCAL_YR ))
ADD (CONSTRAINT LD_CSFTRCKR_OVRD_TR2 FOREIGN KEY (
      UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD )
REFERENCES CA_OBJECT_CODE_T (
      UNIV_FISCAL_YR, FIN_COA_CD, FIN_OBJECT_CD ))
ADD (CONSTRAINT LD_CSFTRCKR_OVRD_TR4 FOREIGN KEY (
      FIN_COA_CD, ACCOUNT_NBR )
REFERENCES CA_ACCOUNT_T (
      FIN_COA_CD, ACCOUNT_NBR ))
/