ALTER TABLE LD_EXP_TRNFR_DOC_T
ADD (CONSTRAINT LD_EXP_TRNFR_DOC_TR1 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR ))
ADD (CONSTRAINT LD_EXP_TRNFR_DOC_TR2 FOREIGN KEY (
      FDOC_POST_YR, FDOC_POST_PRD_CD )
REFERENCES SH_ACCT_PERIOD_T (
      UNIV_FISCAL_YR, UNIV_FISCAL_PRD_CD ))
/