ALTER TABLE LD_LABOR_OBJ_T
ADD (CONSTRAINT LD_LABOR_OBJ_TR2 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT LD_LABOR_OBJ_TR3 FOREIGN KEY (
      POS_OBJ_GRP_CD )
REFERENCES LD_POS_OBJ_GRP_T (
      POS_OBJ_GRP_CD ))
ADD (CONSTRAINT LD_LABOR_OBJ_TR4 FOREIGN KEY (
      UNIV_FISCAL_YR )
REFERENCES FS_OPTION_T (
      UNIV_FISCAL_YR ))
/