ALTER TABLE PDP_PMT_ACCT_HIST_T
ADD (CONSTRAINT PDP_PMT_ACCT_HIST_TR1 FOREIGN KEY (
      PMT_ACCT_DTL_ID )
REFERENCES PDP_PMT_ACCT_DTL_T (
      PMT_ACCT_DTL_ID ) ON DELETE SET NULL )
ADD (CONSTRAINT PDP_PMT_ACCT_HIST_TR2 FOREIGN KEY (
      ACCTG_CHG_CD )
REFERENCES PDP_ACCTG_CHG_CD_T (
      ACCTG_CHG_CD ) ON DELETE SET NULL )
/