ALTER TABLE PDP_CUST_BNK_T
ADD (CONSTRAINT PDP_CUST_BNK_TR1 FOREIGN KEY (
      CUST_ID )
REFERENCES PDP_CUST_PRFL_T (
      CUST_ID ) ON DELETE CASCADE )
ADD (CONSTRAINT PDP_CUST_BNK_TR2 FOREIGN KEY (
      BNK_ID )
REFERENCES PDP_BNK_CD_T (
      BNK_ID ) ON DELETE SET NULL )
ADD (CONSTRAINT PDP_CUST_BNK_TR3 FOREIGN KEY (
      DISB_TYP_CD )
REFERENCES PDP_DISB_TYP_CD_T (
      DISB_TYP_CD ) ON DELETE SET NULL )
/