ALTER TABLE PDP_DOC_TYP_CD_T
ADD (CONSTRAINT PDP_DOC_TYP_CD_TR1 FOREIGN KEY (
      TRN_TYP_CD )
REFERENCES PDP_TRN_TYP_CD_T (
      TRN_TYP_CD ) ON DELETE SET NULL )
ADD (CONSTRAINT PDP_DOC_TYP_CD_TR2 FOREIGN KEY (
      DISB_TYP_CD )
REFERENCES PDP_DISB_TYP_CD_T (
      DISB_TYP_CD ) ON DELETE SET NULL )
/