ALTER TABLE PUR_AP_ORG_PARM_T
ADD (CONSTRAINT PUR_AP_ORG_PARM_TR1 FOREIGN KEY (
      FIN_COA_CD )
REFERENCES CA_CHART_T (
      FIN_COA_CD ))
ADD (CONSTRAINT PUR_AP_ORG_PARM_TR2 FOREIGN KEY (
      FIN_COA_CD, ORG_CD )
REFERENCES CA_ORG_T (
      FIN_COA_CD, ORG_CD ))
/