ALTER TABLE PUR_ASGN_CONTR_MGR_DTL_T
ADD (CONSTRAINT PUR_ASGN_CONTR_MGR_DTL_TR1 FOREIGN KEY (
      REQS_ID )
REFERENCES PUR_REQS_T (
      REQS_ID ))
ADD (CONSTRAINT PUR_ASGN_CONTR_MGR_DTL_TR2 FOREIGN KEY (
      CONTR_MGR_CD )
REFERENCES PUR_CONTR_MGR_T (
      CONTR_MGR_CD ))
ADD (CONSTRAINT PUR_ASGN_CONTR_MGR_DTL_TR3 FOREIGN KEY (
      FDOC_NBR )
REFERENCES PUR_ASGN_CONTR_MGR_T (
      FDOC_NBR ))
/