ALTER TABLE PUR_AP_BLDG_PARM_T
ADD (CONSTRAINT PUR_AP_BLDG_PARM_TR1 FOREIGN KEY (
      CAMPUS_CD, BLDG_CD )
REFERENCES SH_BUILDING_T (
      CAMPUS_CD, BLDG_CD ))
ADD (CONSTRAINT PUR_AP_BLDG_PARM_TR2 FOREIGN KEY (
      CAMPUS_CD )
REFERENCES SH_CAMPUS_T (
      CAMPUS_CD ))
/