ALTER TABLE PUR_AP_CMP_PARM_T
ADD (CONSTRAINT PUR_AP_CMP_PARM_TR1 FOREIGN KEY (
      CAMPUS_CD )
REFERENCES SH_CAMPUS_T (
      CAMPUS_CD ))
ADD (CONSTRAINT PUR_AP_CMP_PARM_TR2 FOREIGN KEY (
      PUR_DEPT_ST_CD )
REFERENCES SH_STATE_T (
      POSTAL_STATE_CD ))
ADD (CONSTRAINT PUR_AP_CMP_PARM_TR3 FOREIGN KEY (
      PUR_DEPT_CNTRY_CD )
REFERENCES SH_COUNTRY_T (
      POSTAL_CNTRY_CD ))
/