ALTER TABLE PUR_COMM_CONTR_MGR_T
ADD (CONSTRAINT PUR_COMM_CONTR_MGR_TR1 FOREIGN KEY (
      PUR_COMM_CD )
REFERENCES PUR_COMM_T (
      PUR_COMM_CD ))
ADD (CONSTRAINT PUR_COMM_CONTR_MGR_TR2 FOREIGN KEY (
      CAMPUS_CD )
REFERENCES SH_CAMPUS_T (
      CAMPUS_CD ))
ADD (CONSTRAINT PUR_COMM_CONTR_MGR_TR3 FOREIGN KEY (
      CONTR_MGR_CD )
REFERENCES PUR_CONTR_MGR_T (
      CONTR_MGR_CD ))
/
