ALTER TABLE PUR_VNDR_COMM_T
ADD (CONSTRAINT PUR_VNDR_COMM_TR1 FOREIGN KEY (
      VNDR_HDR_GNRTD_ID,
      VNDR_DTL_ASND_ID )
REFERENCES PUR_VNDR_DTL_T (
      VNDR_HDR_GNRTD_ID,
      VNDR_DTL_ASND_ID ))
/
