ALTER TABLE PUR_RCVNG_COR_T
ADD (CONSTRAINT PUR_RCVNG_COR_TR1 FOREIGN KEY (
      RCVNG_LN_FDOC_NBR )
REFERENCES PUR_RCVNG_LN_T (
      FDOC_NBR)) 
ADD (CONSTRAINT PUR_RCVNG_COR_TR2 FOREIGN KEY (
      FDOC_NBR )
REFERENCES FP_DOC_HEADER_T (
      FDOC_NBR))
/
