CREATE TABLE QRTZ_BLOB_TRIGGERS 
  ( 
    TRIGGER_NAME VARCHAR2(80) NOT NULL, 
    TRIGGER_GROUP VARCHAR2(80) NOT NULL, 
    BLOB_DATA BLOB NULL, 
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP), 
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
        REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP) 
) 
/
