CREATE TABLE QRTZ_SIMPLE_TRIGGERS 
  ( 
    TRIGGER_NAME VARCHAR2(80) NOT NULL, 
    TRIGGER_GROUP VARCHAR2(80) NOT NULL, 
    REPEAT_COUNT NUMBER(7) NOT NULL, 
    REPEAT_INTERVAL NUMBER(12) NOT NULL, 
    TIMES_TRIGGERED NUMBER(7) NOT NULL, 
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP), 
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP) 
) 
/
