CREATE TABLE QRTZ_JOB_LISTENERS 
  ( 
    JOB_NAME VARCHAR2(80) NOT NULL, 
    JOB_GROUP VARCHAR2(80) NOT NULL, 
    JOB_LISTENER VARCHAR2(80) NOT NULL, 
    PRIMARY KEY (JOB_NAME,JOB_GROUP,JOB_LISTENER), 
    FOREIGN KEY (JOB_NAME,JOB_GROUP) 
REFERENCES QRTZ_JOB_DETAILS(JOB_NAME,JOB_GROUP) 
) 
/
