CREATE TABLE QRTZ_TRIGGER_LISTENERS 
  ( 
    TRIGGER_NAME VARCHAR2(80) NOT NULL, 
    TRIGGER_GROUP VARCHAR2(80) NOT NULL, 
    TRIGGER_LISTENER VARCHAR2(80) NOT NULL, 
    PRIMARY KEY (TRIGGER_NAME,TRIGGER_GROUP,TRIGGER_LISTENER), 
    FOREIGN KEY (TRIGGER_NAME,TRIGGER_GROUP) 
REFERENCES QRTZ_TRIGGERS(TRIGGER_NAME,TRIGGER_GROUP) 
) 
/
