CREATE INDEX AR_INV_PMT_ITM_TI2 ON AR_INV_PMT_ITM_T(
        FIN_COA_CD,
        ACCOUNT_NBR )
/
CREATE INDEX AR_INV_PMT_ITM_TI3 ON AR_INV_PMT_ITM_T(
        UNIV_FISCAL_YR,
        FIN_COA_CD,
        FIN_OBJECT_CD )
/
