CREATE INDEX CM_CPTLAST_HDR_TI2 ON CM_CPTLAST_HDR_T(
        CPTLAST_NBR )
/
CREATE INDEX CM_CPTLAST_HDR_TI3 ON CM_CPTLAST_HDR_T(
        ORG_OWNER_COA_CD,
        ORG_OWNER_ACCT_NBR )
/
CREATE INDEX CM_CPTLAST_HDR_TI4 ON CM_CPTLAST_HDR_T(
        AST_REP_UNVL_ID )
/
