###############################################################################
# $Id: Makefile,v 1.1 2006-08-08 23:17:05 dbeutel Exp $
###############################################################################

SUB_DIRS = cpp
ALL_SUB_DIRS = $(SUB_DIRS)

ifndef TOPDIR
TOPDIR  = $(shell pwd)/..
endif

include $(TOPDIR)/scripts/Config.make
include $(TOPDIR)/scripts/Rules.make
