/* Run in KULDBA */
/* FINAL VERSION WAS NOT TESTED due to some ad hoc SQL between prior and final */

/* 1a) */
truncate table ER_BDGT_DOC_T;

/* 1b) */
-- remove non-current & unneeded workgroups
DELETE
  FROM en_wrkgrp_ext_dta_t
  WHERE wrkgrp_ext_id IN (SELECT wrkgrp_ext_id FROM en_wrkgrp_ext_t
  WHERE wrkgrp_id IN (SELECT wrkgrp_id FROM en_wrkgrp_t
    WHERE (wrkgrp_nm IN (
  '3223ss'
, '3223ssy'
, '322hd'
, 'adf'
, 'ChartOrgWGTest1'
, 'ChartOrgWGTest4'
, 'ChartOrgWGTest5'
, 'EasterBunny0'
, 'EasterBunny12'
, 'EasterBunny323'
, 'EasterBunny44'
, 'EasterBunny775'
, 'EasterBunny775'
, 'EasterBunny777'
, 'EasterBunny9'
, 'EasterBunny99'
, 'KUALI_AAPOSREV'
, 'KUALI_ABM'
, 'KUALI_AD'
, 'KUALI_AE'
, 'KUALI_AR'
, 'KUALI_ARGROUP'
, 'KUALI_ARLB66057'
, 'KUALI_ARLB66248'
, 'KUALI_ARLB66271'
, 'KUALI_ARLB66812'
, 'KUALI_ARLB66867'
, 'KUALI_ARLOCKBOX'
, 'KUALI_BARCODE'
, 'KUALI_BLACPOS'
, 'KUALI_BLCAMS'
, 'KUALI_BLCAMSSY'
, 'KUALI_BLSTPOS'
, 'KUALI_BOOKBUSOFF'
, 'KUALI_BSI_ADMIN'
, 'KUALI_BUSINESS'
, 'KUALI_CAMSFM'
, 'KUALI_CAMSIB'
, 'KUALI_CAMSM'
, 'KUALI_CAMSYEND'
, 'KUALI_CREQ_SB'
, 'KUALI_CSERWGRP'
, 'KUALI_DALLARD'
, 'KUALI_EAACPOS'
, 'KUALI_EACAMSM'
, 'KUALI_EACAMSSY'
, 'KUALI_EASTPOS'
, 'KUALI_EFT'
, 'KUALI_ETFONEHOME'
, 'KUALI_FMSCRV'
, 'KUALI_FMSET'
, 'KUALI_FMSLADJ'
, 'KUALI_FWACPOS'
, 'KUALI_GDSM'
, 'KUALI_HERRON'
, 'KUALI_HUNT'
, 'KUALI_IMUBUSOFF'
, 'KUALI_INACPOS'
, 'KUALI_INCAMS'
, 'KUALI_INCAMSM'
, 'KUALI_INSTPOS'
, 'KUALI_INSURANCE'
, 'KUALI_IUOTPOS'
, 'KUALI_IUPUICRV'
, 'KUALI_KOACPOS'
, 'KUALI_KOCAMSM'
, 'KUALI_KOCAMSSY'
, 'KUALI_KOCRV'
, 'KUALI_KOPURCHASE'
, 'KUALI_KOSTPOS'
, 'KUALI_MATERIEL'
, 'KUALI_MDEP PAYRL'
, 'KUALI_MDEP PYRL'
, 'KUALI_MERP-SIGNF'
, 'KUALI_NWACPOS'
, 'KUALI_NWCALMS'
, 'KUALI_NWCAMSM'
, 'KUALI_NWSTPOS'
, 'KUALI_OCCAMS'
, 'KUALI_OCCAMSM'
, 'KUALI_OTTEST'
, 'KUALI_PADAPPROVE'
, 'KUALI_PATH-FISC'
, 'KUALI_PAYROLL'
, 'KUALI_PED'
, 'KUALI_PLANTFUND'
, 'KUALI_PLAYING'
, 'KUALI_POSJOBSACD'
, 'KUALI_PSWATSON'
, 'KUALI_RECSBA'
, 'KUALI_RM FIN'
, 'KUALI_RMINMAN'
, 'tempcal'
, 'test_dmu'
, 'test1'
, 'test4321'
, 'KUALI_SBACPOS'
, 'KUALI_SBCAMS'
, 'KUALI_SBCAMSM'
, 'KUALI_SBPURCHASE'
, 'KUALI_SBSTPOS'
, 'KUALI_SEACPOS'
, 'KUALI_SECAMS'
, 'KUALI_SECAMSM'
, 'KUALI_SEPURCHASE'
, 'KUALI_SESTPOS'
, 'KUALI_TELCWGRP'
, 'KUALI_TEST'
, 'KUALI_UAACAD'
, 'KUALI_UCSAPPROVE'
, 'KUALI_UCSBLAPPR'
, 'KUALI_UCSTELAPPR'
, 'KUALI_UCSVWGRP'
, 'KUALI_UHRRECORDS'
, 'KUALI_WEST'
, 'KUasdf'
, 'TestBus1'
, 'TestBusCO1'
, 'testgroup'
, 'TestingChartOrg1'
, 'testingsu'
, 'TestMagicalWorkgroupNumeroDeuce'
, 'TestNestedWG'
, 'WorkgroupTestRound3'
, 'KUALI_AREA'
, 'KUALI_INSRFA'
, 'KUALI_ROLE_ACCOUNTS_RECIEVABLE_SUPERVISOR'
, 'KUALI_ROLE_CAB_USER'
, 'KUALI_ROLE_CAMS_ADMIN'
, 'AthContent'
, 'AthleticContent'
)
	AND wrkgrp_nm not in (select wrkgrp_nm from CG_AWD_T)
	AND wrkgrp_nm not in (select qstn_typ_wrkgrp_nm from ER_QSTN_TYP_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CASHIER_ITM_IN_PROC_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CSH_DRWR_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_SB_CTRL_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from SH_PARM_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select blnkt_appr_wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_RTE_NODE_T)
	AND wrkgrp_id not in (select rule_rsp_nm from EN_RULE_RSP_T where RULE_RSP_TYP = 'G')
)
		OR wrkgrp_cur_ind = 0
		OR wrkgrp_actv_ind = 0
)
)
/

DELETE
  FROM en_wrkgrp_ext_t
  WHERE wrkgrp_id IN (SELECT wrkgrp_id FROM en_wrkgrp_t
    WHERE (wrkgrp_nm IN (
  '3223ss'
, '3223ssy'
, '322hd'
, 'adf'
, 'ChartOrgWGTest1'
, 'ChartOrgWGTest4'
, 'ChartOrgWGTest5'
, 'EasterBunny0'
, 'EasterBunny12'
, 'EasterBunny323'
, 'EasterBunny44'
, 'EasterBunny775'
, 'EasterBunny775'
, 'EasterBunny777'
, 'EasterBunny9'
, 'EasterBunny99'
, 'KUALI_AAPOSREV'
, 'KUALI_ABM'
, 'KUALI_AD'
, 'KUALI_AE'
, 'KUALI_AR'
, 'KUALI_ARGROUP'
, 'KUALI_ARLB66057'
, 'KUALI_ARLB66248'
, 'KUALI_ARLB66271'
, 'KUALI_ARLB66812'
, 'KUALI_ARLB66867'
, 'KUALI_ARLOCKBOX'
, 'KUALI_BARCODE'
, 'KUALI_BLACPOS'
, 'KUALI_BLCAMS'
, 'KUALI_BLCAMSSY'
, 'KUALI_BLSTPOS'
, 'KUALI_BOOKBUSOFF'
, 'KUALI_BSI_ADMIN'
, 'KUALI_BUSINESS'
, 'KUALI_CAMSFM'
, 'KUALI_CAMSIB'
, 'KUALI_CAMSM'
, 'KUALI_CAMSYEND'
, 'KUALI_CREQ_SB'
, 'KUALI_CSERWGRP'
, 'KUALI_DALLARD'
, 'KUALI_EAACPOS'
, 'KUALI_EACAMSM'
, 'KUALI_EACAMSSY'
, 'KUALI_EASTPOS'
, 'KUALI_EFT'
, 'KUALI_ETFONEHOME'
, 'KUALI_FMSCRV'
, 'KUALI_FMSET'
, 'KUALI_FMSLADJ'
, 'KUALI_FWACPOS'
, 'KUALI_GDSM'
, 'KUALI_HERRON'
, 'KUALI_HUNT'
, 'KUALI_IMUBUSOFF'
, 'KUALI_INACPOS'
, 'KUALI_INCAMS'
, 'KUALI_INCAMSM'
, 'KUALI_INSTPOS'
, 'KUALI_INSURANCE'
, 'KUALI_IUOTPOS'
, 'KUALI_IUPUICRV'
, 'KUALI_KOACPOS'
, 'KUALI_KOCAMSM'
, 'KUALI_KOCAMSSY'
, 'KUALI_KOCRV'
, 'KUALI_KOPURCHASE'
, 'KUALI_KOSTPOS'
, 'KUALI_MATERIEL'
, 'KUALI_MDEP PAYRL'
, 'KUALI_MDEP PYRL'
, 'KUALI_MERP-SIGNF'
, 'KUALI_NWACPOS'
, 'KUALI_NWCALMS'
, 'KUALI_NWCAMSM'
, 'KUALI_NWSTPOS'
, 'KUALI_OCCAMS'
, 'KUALI_OCCAMSM'
, 'KUALI_OTTEST'
, 'KUALI_PADAPPROVE'
, 'KUALI_PATH-FISC'
, 'KUALI_PAYROLL'
, 'KUALI_PED'
, 'KUALI_PLANTFUND'
, 'KUALI_PLAYING'
, 'KUALI_POSJOBSACD'
, 'KUALI_PSWATSON'
, 'KUALI_RECSBA'
, 'KUALI_RM FIN'
, 'KUALI_RMINMAN'
, 'tempcal'
, 'test_dmu'
, 'test1'
, 'test4321'
, 'KUALI_SBACPOS'
, 'KUALI_SBCAMS'
, 'KUALI_SBCAMSM'
, 'KUALI_SBPURCHASE'
, 'KUALI_SBSTPOS'
, 'KUALI_SEACPOS'
, 'KUALI_SECAMS'
, 'KUALI_SECAMSM'
, 'KUALI_SEPURCHASE'
, 'KUALI_SESTPOS'
, 'KUALI_TELCWGRP'
, 'KUALI_TEST'
, 'KUALI_UAACAD'
, 'KUALI_UCSAPPROVE'
, 'KUALI_UCSBLAPPR'
, 'KUALI_UCSTELAPPR'
, 'KUALI_UCSVWGRP'
, 'KUALI_UHRRECORDS'
, 'KUALI_WEST'
, 'KUasdf'
, 'TestBus1'
, 'TestBusCO1'
, 'testgroup'
, 'TestingChartOrg1'
, 'testingsu'
, 'TestMagicalWorkgroupNumeroDeuce'
, 'TestNestedWG'
, 'WorkgroupTestRound3'
, 'KUALI_AREA'
, 'KUALI_INSRFA'
, 'KUALI_ROLE_ACCOUNTS_RECIEVABLE_SUPERVISOR'
, 'KUALI_ROLE_CAB_USER'
, 'KUALI_ROLE_CAMS_ADMIN'
, 'AthContent'
, 'AthleticContent'
)
	AND wrkgrp_nm not in (select wrkgrp_nm from CG_AWD_T)
	AND wrkgrp_nm not in (select qstn_typ_wrkgrp_nm from ER_QSTN_TYP_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CASHIER_ITM_IN_PROC_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CSH_DRWR_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_SB_CTRL_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from SH_PARM_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select blnkt_appr_wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_RTE_NODE_T)
	AND wrkgrp_id not in (select rule_rsp_nm from EN_RULE_RSP_T where RULE_RSP_TYP = 'G')
)
		OR wrkgrp_cur_ind = 0
		OR wrkgrp_actv_ind = 0
)
/

DELETE
  FROM en_wrkgrp_mbr_t
  WHERE wrkgrp_id IN (SELECT wrkgrp_id FROM en_wrkgrp_t
    WHERE (wrkgrp_nm IN (
  '3223ss'
, '3223ssy'
, '322hd'
, 'adf'
, 'ChartOrgWGTest1'
, 'ChartOrgWGTest4'
, 'ChartOrgWGTest5'
, 'EasterBunny0'
, 'EasterBunny12'
, 'EasterBunny323'
, 'EasterBunny44'
, 'EasterBunny775'
, 'EasterBunny775'
, 'EasterBunny777'
, 'EasterBunny9'
, 'EasterBunny99'
, 'KUALI_AAPOSREV'
, 'KUALI_ABM'
, 'KUALI_AD'
, 'KUALI_AE'
, 'KUALI_AR'
, 'KUALI_ARGROUP'
, 'KUALI_ARLB66057'
, 'KUALI_ARLB66248'
, 'KUALI_ARLB66271'
, 'KUALI_ARLB66812'
, 'KUALI_ARLB66867'
, 'KUALI_ARLOCKBOX'
, 'KUALI_BARCODE'
, 'KUALI_BLACPOS'
, 'KUALI_BLCAMS'
, 'KUALI_BLCAMSSY'
, 'KUALI_BLSTPOS'
, 'KUALI_BOOKBUSOFF'
, 'KUALI_BSI_ADMIN'
, 'KUALI_BUSINESS'
, 'KUALI_CAMSFM'
, 'KUALI_CAMSIB'
, 'KUALI_CAMSM'
, 'KUALI_CAMSYEND'
, 'KUALI_CREQ_SB'
, 'KUALI_CSERWGRP'
, 'KUALI_DALLARD'
, 'KUALI_EAACPOS'
, 'KUALI_EACAMSM'
, 'KUALI_EACAMSSY'
, 'KUALI_EASTPOS'
, 'KUALI_EFT'
, 'KUALI_ETFONEHOME'
, 'KUALI_FMSCRV'
, 'KUALI_FMSET'
, 'KUALI_FMSLADJ'
, 'KUALI_FWACPOS'
, 'KUALI_GDSM'
, 'KUALI_HERRON'
, 'KUALI_HUNT'
, 'KUALI_IMUBUSOFF'
, 'KUALI_INACPOS'
, 'KUALI_INCAMS'
, 'KUALI_INCAMSM'
, 'KUALI_INSTPOS'
, 'KUALI_INSURANCE'
, 'KUALI_IUOTPOS'
, 'KUALI_IUPUICRV'
, 'KUALI_KOACPOS'
, 'KUALI_KOCAMSM'
, 'KUALI_KOCAMSSY'
, 'KUALI_KOCRV'
, 'KUALI_KOPURCHASE'
, 'KUALI_KOSTPOS'
, 'KUALI_MATERIEL'
, 'KUALI_MDEP PAYRL'
, 'KUALI_MDEP PYRL'
, 'KUALI_MERP-SIGNF'
, 'KUALI_NWACPOS'
, 'KUALI_NWCALMS'
, 'KUALI_NWCAMSM'
, 'KUALI_NWSTPOS'
, 'KUALI_OCCAMS'
, 'KUALI_OCCAMSM'
, 'KUALI_OTTEST'
, 'KUALI_PADAPPROVE'
, 'KUALI_PATH-FISC'
, 'KUALI_PAYROLL'
, 'KUALI_PED'
, 'KUALI_PLANTFUND'
, 'KUALI_PLAYING'
, 'KUALI_POSJOBSACD'
, 'KUALI_PSWATSON'
, 'KUALI_RECSBA'
, 'KUALI_RM FIN'
, 'KUALI_RMINMAN'
, 'tempcal'
, 'test_dmu'
, 'test1'
, 'test4321'
, 'KUALI_SBACPOS'
, 'KUALI_SBCAMS'
, 'KUALI_SBCAMSM'
, 'KUALI_SBPURCHASE'
, 'KUALI_SBSTPOS'
, 'KUALI_SEACPOS'
, 'KUALI_SECAMS'
, 'KUALI_SECAMSM'
, 'KUALI_SEPURCHASE'
, 'KUALI_SESTPOS'
, 'KUALI_TELCWGRP'
, 'KUALI_TEST'
, 'KUALI_UAACAD'
, 'KUALI_UCSAPPROVE'
, 'KUALI_UCSBLAPPR'
, 'KUALI_UCSTELAPPR'
, 'KUALI_UCSVWGRP'
, 'KUALI_UHRRECORDS'
, 'KUALI_WEST'
, 'KUasdf'
, 'TestBus1'
, 'TestBusCO1'
, 'testgroup'
, 'TestingChartOrg1'
, 'testingsu'
, 'TestMagicalWorkgroupNumeroDeuce'
, 'TestNestedWG'
, 'WorkgroupTestRound3'
, 'KUALI_AREA'
, 'KUALI_INSRFA'
, 'KUALI_ROLE_ACCOUNTS_RECIEVABLE_SUPERVISOR'
, 'KUALI_ROLE_CAB_USER'
, 'KUALI_ROLE_CAMS_ADMIN'
, 'AthContent'
, 'AthleticContent'
)
	AND wrkgrp_nm not in (select wrkgrp_nm from CG_AWD_T)
	AND wrkgrp_nm not in (select qstn_typ_wrkgrp_nm from ER_QSTN_TYP_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CASHIER_ITM_IN_PROC_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CSH_DRWR_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_SB_CTRL_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from SH_PARM_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select blnkt_appr_wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_RTE_NODE_T)
	AND wrkgrp_id not in (select rule_rsp_nm from EN_RULE_RSP_T where RULE_RSP_TYP = 'G')
)
		OR wrkgrp_cur_ind = 0
		OR wrkgrp_actv_ind = 0
)
/

DELETE FROM en_wrkgrp_t
    WHERE (wrkgrp_nm IN (
  '3223ss'
, '3223ssy'
, '322hd'
, 'adf'
, 'ChartOrgWGTest1'
, 'ChartOrgWGTest4'
, 'ChartOrgWGTest5'
, 'EasterBunny0'
, 'EasterBunny12'
, 'EasterBunny323'
, 'EasterBunny44'
, 'EasterBunny775'
, 'EasterBunny775'
, 'EasterBunny777'
, 'EasterBunny9'
, 'EasterBunny99'
, 'KUALI_AAPOSREV'
, 'KUALI_ABM'
, 'KUALI_AD'
, 'KUALI_AE'
, 'KUALI_AR'
, 'KUALI_ARGROUP'
, 'KUALI_ARLB66057'
, 'KUALI_ARLB66248'
, 'KUALI_ARLB66271'
, 'KUALI_ARLB66812'
, 'KUALI_ARLB66867'
, 'KUALI_ARLOCKBOX'
, 'KUALI_BARCODE'
, 'KUALI_BLACPOS'
, 'KUALI_BLCAMS'
, 'KUALI_BLCAMSSY'
, 'KUALI_BLSTPOS'
, 'KUALI_BOOKBUSOFF'
, 'KUALI_BSI_ADMIN'
, 'KUALI_BUSINESS'
, 'KUALI_CAMSFM'
, 'KUALI_CAMSIB'
, 'KUALI_CAMSM'
, 'KUALI_CAMSYEND'
, 'KUALI_CREQ_SB'
, 'KUALI_CSERWGRP'
, 'KUALI_DALLARD'
, 'KUALI_EAACPOS'
, 'KUALI_EACAMSM'
, 'KUALI_EACAMSSY'
, 'KUALI_EASTPOS'
, 'KUALI_EFT'
, 'KUALI_ETFONEHOME'
, 'KUALI_FMSCRV'
, 'KUALI_FMSET'
, 'KUALI_FMSLADJ'
, 'KUALI_FWACPOS'
, 'KUALI_GDSM'
, 'KUALI_HERRON'
, 'KUALI_HUNT'
, 'KUALI_IMUBUSOFF'
, 'KUALI_INACPOS'
, 'KUALI_INCAMS'
, 'KUALI_INCAMSM'
, 'KUALI_INSTPOS'
, 'KUALI_INSURANCE'
, 'KUALI_IUOTPOS'
, 'KUALI_IUPUICRV'
, 'KUALI_KOACPOS'
, 'KUALI_KOCAMSM'
, 'KUALI_KOCAMSSY'
, 'KUALI_KOCRV'
, 'KUALI_KOPURCHASE'
, 'KUALI_KOSTPOS'
, 'KUALI_MATERIEL'
, 'KUALI_MDEP PAYRL'
, 'KUALI_MDEP PYRL'
, 'KUALI_MERP-SIGNF'
, 'KUALI_NWACPOS'
, 'KUALI_NWCALMS'
, 'KUALI_NWCAMSM'
, 'KUALI_NWSTPOS'
, 'KUALI_OCCAMS'
, 'KUALI_OCCAMSM'
, 'KUALI_OTTEST'
, 'KUALI_PADAPPROVE'
, 'KUALI_PATH-FISC'
, 'KUALI_PAYROLL'
, 'KUALI_PED'
, 'KUALI_PLANTFUND'
, 'KUALI_PLAYING'
, 'KUALI_POSJOBSACD'
, 'KUALI_PSWATSON'
, 'KUALI_RECSBA'
, 'KUALI_RM FIN'
, 'KUALI_RMINMAN'
, 'tempcal'
, 'test_dmu'
, 'test1'
, 'test4321'
, 'KUALI_SBACPOS'
, 'KUALI_SBCAMS'
, 'KUALI_SBCAMSM'
, 'KUALI_SBPURCHASE'
, 'KUALI_SBSTPOS'
, 'KUALI_SEACPOS'
, 'KUALI_SECAMS'
, 'KUALI_SECAMSM'
, 'KUALI_SEPURCHASE'
, 'KUALI_SESTPOS'
, 'KUALI_TELCWGRP'
, 'KUALI_TEST'
, 'KUALI_UAACAD'
, 'KUALI_UCSAPPROVE'
, 'KUALI_UCSBLAPPR'
, 'KUALI_UCSTELAPPR'
, 'KUALI_UCSVWGRP'
, 'KUALI_UHRRECORDS'
, 'KUALI_WEST'
, 'KUasdf'
, 'TestBus1'
, 'TestBusCO1'
, 'testgroup'
, 'TestingChartOrg1'
, 'testingsu'
, 'TestMagicalWorkgroupNumeroDeuce'
, 'TestNestedWG'
, 'WorkgroupTestRound3'
, 'KUALI_AREA'
, 'KUALI_INSRFA'
, 'KUALI_ROLE_ACCOUNTS_RECIEVABLE_SUPERVISOR'
, 'KUALI_ROLE_CAB_USER'
, 'KUALI_ROLE_CAMS_ADMIN'
, 'AthContent'
, 'AthleticContent'
)
	AND wrkgrp_nm not in (select wrkgrp_nm from CG_AWD_T)
	AND wrkgrp_nm not in (select qstn_typ_wrkgrp_nm from ER_QSTN_TYP_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CASHIER_ITM_IN_PROC_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_CSH_DRWR_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from FP_SB_CTRL_T)
	AND wrkgrp_nm not in (select wrkgrp_nm from SH_PARM_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select blnkt_appr_wrkgrp_id from EN_DOC_TYP_T)
	AND wrkgrp_id not in (select wrkgrp_id from EN_RTE_NODE_T)
	AND wrkgrp_id not in (select rule_rsp_nm from EN_RULE_RSP_T where RULE_RSP_TYP = 'G')
)
		OR wrkgrp_cur_ind = 0
		OR wrkgrp_actv_ind = 0
/

UPDATE en_wrkgrp_t SET doc_hdr_id = -1 WHERE doc_hdr_id != -1
/

/* put KHUNTLEY in any empty workgroups */
INSERT INTO en_wrkgrp_mbr_t
  SELECT '6162502038', wrkgrp_id, 'U', wrkgrp_ver_nbr, 1
    FROM en_wrkgrp_t
   WHERE (wrkgrp_id,wrkgrp_ver_nbr) NOT IN
         (SELECT wrkgrp_id,wrkgrp_ver_nbr FROM en_wrkgrp_mbr_t)
/

/* 1c) */
-- remove orphan members
DELETE FROM en_wrkgrp_mbr_t
    WHERE NOT EXISTS ( SELECT 'x' FROM en_wrkgrp_t 
        WHERE wrkgrp_id = en_wrkgrp_mbr_t.wrkgrp_id
          AND wrkgrp_ver_nbr = en_wrkgrp_mbr_t.wrkgrp_ver_nbr 
    )
/  

/* 1d) */
UPDATE ca_obj_sub_type_t
    SET fin_obj_sub_typ_nm = 'TRANSFERS - NONMANDATORY'
    WHERE fin_obj_sub_typ_cd = 'TN'
/

/* 1e) */
-- rename the "STATE OF INDIANA" sub fund groups            
UPDATE ca_sub_fund_grp_t 
SET sub_fund_grp_desc = 'STATE FUNDS'
WHERE sub_fund_grp_desc = 'STATE OF INDIANA'
/

/* 1h) */
-- remove references to "IU" and specific object codes
UPDATE fp_dv_pmt_reas_t 
    SET dv_pmt_reas_desc = REPLACE( dv_pmt_reas_desc, ' IU ', ' University ' )
/

/* 1i) */
-- Tax Control Name referenced "IU"       
UPDATE fp_dv_tax_ctrl_t
   SET dv_tax_ctrl_nm = 'Approved for Employee'
   WHERE dv_payee_txctrl_cd = 'A'
/

-- cleanup unused documents and old versions
DELETE
  FROM en_rte_node_lnk_t a
  WHERE from_rte_node_id IN ( SELECT rte_node_id FROM en_rte_node_t
  WHERE doc_typ_id IN (SELECT doc_typ_id FROM en_doc_typ_t
    WHERE doc_typ_nm IN (
  'AccountingPeriodMainanceDocument'
, 'BusinessRuleMaintenanceDocument'
, 'KualiAccountGuideline'
, 'KualiApplicationConstantMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiBaseTestDocument'
, 'KualiBudgetBaseCodeMaintenanceDocument'
, 'KualiBudgetPurposeCodeMaintenanceDocument'
, 'KualiBusinessRuleGroupMaintenanceDocument'
, 'KualiBusinessRuleMaintenanceDocument'
, 'KualiCatalogOfFederalDomesticAssistanceReferenceMaintenanceDocument'
, 'KualiCloseDocument'
, 'KualiCollectorFileMaintenanceDocument'
, 'KualiControlAttributeTypeMaintenanceDocument'
, 'KualiDisbursementVoucherPaymentReasonMaintenanceDocument'
, 'KualiErrorCertificationReportPeriodStatusMaintenanceDocument'
, 'KualiFederalFundedMaintenanceDocument'
, 'KualiFinancialSystemParameterSecurityMaintenanceDocument'
, 'KualiGeneralErrorCorrectionYearEndDocument'
, 'KualiGlobalAccountMaintenanceDocument'
, 'KualiGrantDescriptionMaintenanceDocument'
, 'KualiGroupMaintenanceDocument'
, 'KualiHomeOriginationMaintenanceDocument'
, 'KualiIndirectCostLookupMaintenanceDocument'
, 'KualiIndirectCostRecoveryThresholdMaintenanceDocument'
, 'KualiKeywordMaintenanceDocument'
, 'KualiLaborObjectBenefitMaintenanceDocument'
, 'KualiLaborObjectGroupMaintenanceDocument'
, 'KualiLedgerErrorCorrectionDocument'
, 'KualiLetterOfCreditFundGroupMaintenanceDocument'
, 'KualiObjectCodeRestrictionsMaintenanceDocument'
, 'KualiOrganizationReversionChangeMaintenanceDocument'
, 'KualiOrgOptionsMaintenanceDocument'
, 'KualiProjectDirectorMaintenanceDocument'
, 'KualiPurchaseOrderPrintDocument'
, 'KualiReportingFinancialDocument'
, 'KualiReportingTransferOfFundsDocument'
, 'KualiResearchAdminPreAwartMaintenanceDocument'
, 'KualiRoutingFormResearchRiskTypeDocument'
, 'KualiSharedStateMaintenanceDocument'
, 'KualiSharedZipCodeMaintenanceDocument'
, 'KualiSubmissionTypeMaintenanceDocument'
, 'KualiUserMaintenanceDocument'
, 'KualiVendorStatusMaintenanceDocument'
, 'KualiYearEndDistIncExpDocument'
, 'KualiYETESTDistributionOfIncomeAndExpenseDocument'
, 'KualiZipCodeMaintenanceDocument'
, 'MyTestDocumentType'
, 'ProgramMaintenanceDocument'
, 'Test Disbursement Voucher Document'
, 'TestWorkflowDocument'
, 'TestWorkflowKualiInternalBillingDocument'
)
		OR doc_typ_cur_ind = 0
)
)
/

DELETE
  FROM en_rte_node_lnk_t a
  WHERE to_rte_node_id IN ( SELECT rte_node_id FROM en_rte_node_t
  WHERE doc_typ_id IN (SELECT doc_typ_id FROM en_doc_typ_t
    WHERE doc_typ_nm IN (
  'AccountingPeriodMainanceDocument'
, 'BusinessRuleMaintenanceDocument'
, 'KualiAccountGuideline'
, 'KualiApplicationConstantMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiBaseTestDocument'
, 'KualiBudgetBaseCodeMaintenanceDocument'
, 'KualiBudgetPurposeCodeMaintenanceDocument'
, 'KualiBusinessRuleGroupMaintenanceDocument'
, 'KualiBusinessRuleMaintenanceDocument'
, 'KualiCatalogOfFederalDomesticAssistanceReferenceMaintenanceDocument'
, 'KualiCloseDocument'
, 'KualiCollectorFileMaintenanceDocument'
, 'KualiControlAttributeTypeMaintenanceDocument'
, 'KualiDisbursementVoucherPaymentReasonMaintenanceDocument'
, 'KualiErrorCertificationReportPeriodStatusMaintenanceDocument'
, 'KualiFederalFundedMaintenanceDocument'
, 'KualiFinancialSystemParameterSecurityMaintenanceDocument'
, 'KualiGeneralErrorCorrectionYearEndDocument'
, 'KualiGlobalAccountMaintenanceDocument'
, 'KualiGrantDescriptionMaintenanceDocument'
, 'KualiGroupMaintenanceDocument'
, 'KualiHomeOriginationMaintenanceDocument'
, 'KualiIndirectCostLookupMaintenanceDocument'
, 'KualiIndirectCostRecoveryThresholdMaintenanceDocument'
, 'KualiKeywordMaintenanceDocument'
, 'KualiLaborObjectBenefitMaintenanceDocument'
, 'KualiLaborObjectGroupMaintenanceDocument'
, 'KualiLedgerErrorCorrectionDocument'
, 'KualiLetterOfCreditFundGroupMaintenanceDocument'
, 'KualiObjectCodeRestrictionsMaintenanceDocument'
, 'KualiOrganizationReversionChangeMaintenanceDocument'
, 'KualiOrgOptionsMaintenanceDocument'
, 'KualiProjectDirectorMaintenanceDocument'
, 'KualiPurchaseOrderPrintDocument'
, 'KualiReportingFinancialDocument'
, 'KualiReportingTransferOfFundsDocument'
, 'KualiResearchAdminPreAwartMaintenanceDocument'
, 'KualiRoutingFormResearchRiskTypeDocument'
, 'KualiSharedStateMaintenanceDocument'
, 'KualiSharedZipCodeMaintenanceDocument'
, 'KualiSubmissionTypeMaintenanceDocument'
, 'KualiUserMaintenanceDocument'
, 'KualiVendorStatusMaintenanceDocument'
, 'KualiYearEndDistIncExpDocument'
, 'KualiYETESTDistributionOfIncomeAndExpenseDocument'
, 'KualiZipCodeMaintenanceDocument'
, 'MyTestDocumentType'
, 'ProgramMaintenanceDocument'
, 'Test Disbursement Voucher Document'
, 'TestWorkflowDocument'
, 'TestWorkflowKualiInternalBillingDocument'
)
		OR doc_typ_cur_ind = 0
)
)
/

DELETE
  FROM en_rte_node_t a
  WHERE doc_typ_id IN (SELECT doc_typ_id FROM en_doc_typ_t
    WHERE doc_typ_nm IN (
  'AccountingPeriodMainanceDocument'
, 'BusinessRuleMaintenanceDocument'
, 'KualiAccountGuideline'
, 'KualiApplicationConstantMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiBaseTestDocument'
, 'KualiBudgetBaseCodeMaintenanceDocument'
, 'KualiBudgetPurposeCodeMaintenanceDocument'
, 'KualiBusinessRuleGroupMaintenanceDocument'
, 'KualiBusinessRuleMaintenanceDocument'
, 'KualiCatalogOfFederalDomesticAssistanceReferenceMaintenanceDocument'
, 'KualiCloseDocument'
, 'KualiCollectorFileMaintenanceDocument'
, 'KualiControlAttributeTypeMaintenanceDocument'
, 'KualiDisbursementVoucherPaymentReasonMaintenanceDocument'
, 'KualiErrorCertificationReportPeriodStatusMaintenanceDocument'
, 'KualiFederalFundedMaintenanceDocument'
, 'KualiFinancialSystemParameterSecurityMaintenanceDocument'
, 'KualiGeneralErrorCorrectionYearEndDocument'
, 'KualiGlobalAccountMaintenanceDocument'
, 'KualiGrantDescriptionMaintenanceDocument'
, 'KualiGroupMaintenanceDocument'
, 'KualiHomeOriginationMaintenanceDocument'
, 'KualiIndirectCostLookupMaintenanceDocument'
, 'KualiIndirectCostRecoveryThresholdMaintenanceDocument'
, 'KualiKeywordMaintenanceDocument'
, 'KualiLaborObjectBenefitMaintenanceDocument'
, 'KualiLaborObjectGroupMaintenanceDocument'
, 'KualiLedgerErrorCorrectionDocument'
, 'KualiLetterOfCreditFundGroupMaintenanceDocument'
, 'KualiObjectCodeRestrictionsMaintenanceDocument'
, 'KualiOrganizationReversionChangeMaintenanceDocument'
, 'KualiOrgOptionsMaintenanceDocument'
, 'KualiProjectDirectorMaintenanceDocument'
, 'KualiPurchaseOrderPrintDocument'
, 'KualiReportingFinancialDocument'
, 'KualiReportingTransferOfFundsDocument'
, 'KualiResearchAdminPreAwartMaintenanceDocument'
, 'KualiRoutingFormResearchRiskTypeDocument'
, 'KualiSharedStateMaintenanceDocument'
, 'KualiSharedZipCodeMaintenanceDocument'
, 'KualiSubmissionTypeMaintenanceDocument'
, 'KualiUserMaintenanceDocument'
, 'KualiVendorStatusMaintenanceDocument'
, 'KualiYearEndDistIncExpDocument'
, 'KualiYETESTDistributionOfIncomeAndExpenseDocument'
, 'KualiZipCodeMaintenanceDocument'
, 'MyTestDocumentType'
, 'ProgramMaintenanceDocument'
, 'Test Disbursement Voucher Document'
, 'TestWorkflowDocument'
, 'TestWorkflowKualiInternalBillingDocument'
)
		OR doc_typ_cur_ind = 0
)
/

-- clear out bad document types
DELETE 
FROM en_doc_typ_t
    WHERE doc_typ_nm IN (
  'AccountingPeriodMainanceDocument'
, 'BusinessRuleMaintenanceDocument'
, 'KualiAccountGuideline'
, 'KualiApplicationConstantMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiAutomatedReportPeriodMaintenanceDocument'
, 'KualiBaseTestDocument'
, 'KualiBudgetBaseCodeMaintenanceDocument'
, 'KualiBudgetPurposeCodeMaintenanceDocument'
, 'KualiBusinessRuleGroupMaintenanceDocument'
, 'KualiBusinessRuleMaintenanceDocument'
, 'KualiCatalogOfFederalDomesticAssistanceReferenceMaintenanceDocument'
, 'KualiCloseDocument'
, 'KualiCollectorFileMaintenanceDocument'
, 'KualiControlAttributeTypeMaintenanceDocument'
, 'KualiDisbursementVoucherPaymentReasonMaintenanceDocument'
, 'KualiErrorCertificationReportPeriodStatusMaintenanceDocument'
, 'KualiFederalFundedMaintenanceDocument'
, 'KualiFinancialSystemParameterSecurityMaintenanceDocument'
, 'KualiGeneralErrorCorrectionYearEndDocument'
, 'KualiGlobalAccountMaintenanceDocument'
, 'KualiGrantDescriptionMaintenanceDocument'
, 'KualiGroupMaintenanceDocument'
, 'KualiHomeOriginationMaintenanceDocument'
, 'KualiIndirectCostLookupMaintenanceDocument'
, 'KualiIndirectCostRecoveryThresholdMaintenanceDocument'
, 'KualiKeywordMaintenanceDocument'
, 'KualiLaborObjectBenefitMaintenanceDocument'
, 'KualiLaborObjectGroupMaintenanceDocument'
, 'KualiLedgerErrorCorrectionDocument'
, 'KualiLetterOfCreditFundGroupMaintenanceDocument'
, 'KualiObjectCodeRestrictionsMaintenanceDocument'
, 'KualiOrganizationReversionChangeMaintenanceDocument'
, 'KualiOrgOptionsMaintenanceDocument'
, 'KualiProjectDirectorMaintenanceDocument'
, 'KualiPurchaseOrderPrintDocument'
, 'KualiReportingFinancialDocument'
, 'KualiReportingTransferOfFundsDocument'
, 'KualiResearchAdminPreAwartMaintenanceDocument'
, 'KualiRoutingFormResearchRiskTypeDocument'
, 'KualiSharedStateMaintenanceDocument'
, 'KualiSharedZipCodeMaintenanceDocument'
, 'KualiSubmissionTypeMaintenanceDocument'
, 'KualiUserMaintenanceDocument'
, 'KualiVendorStatusMaintenanceDocument'
, 'KualiYearEndDistIncExpDocument'
, 'KualiYETESTDistributionOfIncomeAndExpenseDocument'
, 'KualiZipCodeMaintenanceDocument'
, 'MyTestDocumentType'
, 'ProgramMaintenanceDocument'
, 'Test Disbursement Voucher Document'
, 'TestWorkflowDocument'
, 'TestWorkflowKualiInternalBillingDocument'
)
		OR doc_typ_cur_ind = 0
/

delete en_doc_typ_t where doc_typ_nm like 'KualiBudgetConstruction%'
/

update sh_parm_t set wrkgrp_nm = 'KUALI_ROLE_DV_ADMIN' where wrkgrp_nm = 'KUALI_ROLE_DV_ADMIN KFS-FP'
/
